# Generated by Django 5.1.4 on 2026-08-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('printer_type', models.CharField(choices=[('A4', 'A4'), ('THERMAL', 'Thermal')], default='A4', max_length=20)),
                ('connection_info', models.CharField(blank=True, help_text='Printer name/IP as seen by the OS', max_length=255)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_log_enabled', models.BooleanField(default=True)),
                ('company_name', models.CharField(default='Lakmee Exports Lanka (Pvt) Ltd', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'system settings',
            },
        ),
    ]
