# Generated by Django 5.1.4 on 2026-09-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('tag_prefix', models.CharField(help_text="Prefix used in this org's asset tags, e.g. 'PLD' -> PLD-IT-0001", max_length=10)),
                ('primary_color', models.CharField(default='#A02334', help_text='Hex color, e.g. #A02334', max_length=7)),
                ('logo_filename', models.CharField(blank=True, help_text="Filename under frontend/public/, e.g. 'logo-palladion.png'", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
